# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20160228_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(default='first one', max_length=200),
            preserve_default=False,
        ),
    ]
