# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_content_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='footer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='header',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='footer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='header',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='footer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='header',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='topics',
            field=models.ManyToManyField(blank=True, to='course.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='contents',
            field=models.ManyToManyField(blank=True, to='course.Content'),
        ),
    ]
