# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20160228_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('name', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
    ]
