# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20160229_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='images',
            field=models.ManyToManyField(blank=True, to='course.Image'),
        ),
    ]
