# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 03:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20160302_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='wellOffset',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
    ]
