# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20160302_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='reading',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
