# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_topic_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='reading',
        ),
        migrations.AddField(
            model_name='content',
            name='reading',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
